#!/bin/bash

#this script installs the Shock OS .deb in the current directory

until [[ " ${installed_packages[@]} " == *" pipewire-audio "* ]]
do

    sudo apt update

    sudo apt install pipewire-audio

    installed_packages=($(apt list --installed | awk -F/ '{print $1}' | uniq)) #ChatGPT

done

until [[ " ${installed_packages[@]} " == *" shock-os-metapackage "* ]]
do

    sudo apt install -y ./shockos*

    installed_packages=($(apt list --installed | awk -F/ '{print $1}' | uniq)) #ChatGPT

done

sudo apt update

sudo apt purge -y pluma xterm #gets rid of pluma (because gedit is installed instead), and xterm

sudo apt autopurge -y

sudo apt update

sudo shock-update-manager-refresh
