#!/bin/bash

#this script installs the Shock OS .deb in the current directory

until [[ "$(apt show shock-os-metapackage)" == *"Installed: yes"* ]]
do

    sudo apt update

    sudo apt install -y ./shockos*

done

#the stylepak patch begins (installs Shock OS system GTK themes as Flatpaks)

for theme in $(ls /usr/share/themes | grep shock)
do

    /usr/share/shock/stylepak_themes install-system "$theme"

done

#the stylepak patch ends

sudo apt update

sudo apt purge -y pluma xterm ostree appstream-util #gets rid of pluma (because gedit is installed instead), xterm, ostree, and appstream-util (because ostree and appstream-util are only installed for stylepak to work)

sudo apt autopurge -y

sudo apt update

sudo shock-os-update-manager-refresh
