#!/bin/bash

if [[ "$1" == "mate" ]] || [[ "$1" == "gnome" ]]
then

    echo "$(date '+%A, %B %eth, %Y')" | tee shock-os-core-9-all/usr/share/shock/build-date

    rm -r BUILD-OUT

    mkdir BUILD-OUT

    cp auto-inst BUILD-OUT

    dpkg-deb --build -Zxz shock-os-core-9-all BUILD-OUT

    dpkg-deb --build -Zxz shock-os-"$1"-desktop-9-all BUILD-OUT

else

    echo "ERROR: Must use either 'gnome' or 'mate' as an argument."

fi
