#!/bin/bash

if [[ "$1" == "mate" ]] || [[ "$1" == "gnome" ]]
then

    day=$(date '+%e')

    if [[ "$day" == "11" ]] || [[ "$day" == "12" ]] || [[ "$day" == "13" ]]
    then

      suffix="th"

    else

      case $((day % 10)) in

        1) suffix="st";;

        2) suffix="nd";;

        3) suffix="rd";;

        *) suffix="th";;

      esac

    fi

    echo "$(date "+%A, %B %e$suffix, %Y")" | tee shock-os-core-9-all/usr/share/shock/build-date

    rm -r BUILD-OUT

    mkdir BUILD-OUT

    cp auto-inst BUILD-OUT

    dpkg-deb --build shock-os-core-9-all BUILD-OUT

    dpkg-deb --build shock-os-"$1"-desktop-9-all BUILD-OUT

else

    echo "ERROR: Must use either 'gnome' or 'mate' as an argument."

fi
