#!/bin/bash

echo "$(date '+%A, %B %eth, %Y')" | tee shock-os-core-9.0-all/usr/share/shock/build-date

rm -r BUILD-OUT

mkdir BUILD-OUT

cp auto-inst BUILD-OUT

dpkg-deb --build -Zxz shock-os-core-9.0-all BUILD-OUT

dpkg-deb --build -Zxz shock-os-mate-desktop-9.0-all BUILD-OUT
