#!/bin/bash

#use this in the preupgr or postupgr script in the 9.0 upgrade pack for a smooth transition

#the config file renaming begins

for user_home_dir in /home/*
do

    if [[ -f "$user_home_dir"/.config/shock-slideshow-wallpaper ]]
    then

        source "$user_home_dir"/.config/shock-slideshow-wallpaper

        echo "directory=\"$directory\"

delay=\"$delay\"

random_boolean=\"$random_inorder\"

style=\"$style\"" | tee "$user_home_dir"/.config/shock/slideshow-background

        rm "$user_home_dir"/.config/shock-slideshow-wallpaper

        rm "$user_home_dir"/.config/shock-wallpaper

    fi

    source "$user_home_dir"/.config/shock_themes

    echo "shock_gtk_theme=shock-${lod}-${color}
shock_icon_theme=shock-${lod}-${color}" | tee "$user_home_dir"/.config/shock/themes

    rm "$user_home_dir"/.config/shock_themes

    rm -r "$user_home_dir"/.cache/shock-release-scanner

    mv "$user_home_dir"/.config/shock-welcome-indicator "$user_home_dir"/.config/shock/welcome-indicator

    mv "$user_home_dir"/.config/userlogstat "$user_home_dir"/.config/shock/userlogstat

    mv "$user_home_dir"/.config/shock_fonts "$user_home_dir"/.config/shock/fonts

    mv "$user_home_dir"/.config/shockware-center "$user_home_dir"/.config/shock/shockware-center

    mkdir -p "$user_home_dir"/.themes #THEME BANDAID FIX

    cp -r /usr/share/themes/shock-* "$user_home_dir"/.themes #THEME BANDAID FIX

done

#the config file renaming ends

#the pcstl -> screentime patch begins

chattr -R -i /usr/share/shock-pcstl

rm -r /usr/share/shock-pcstl/*/today

for user_pcstl_dir in /usr/share/shock-pcstl/*
do

    mv "$user_pcstl_dir"/shock-screen-time-limit "$user_pcstl_dir"/dailylimit

done

mkdir -p /usr/share/shock-screentime

mv /usr/share/shock-pcstl/* /usr/share/shock-screentime/

rm -r /usr/share/shock-pcstl

#the pcstl -> screentime patch ends

#NEW POSTINST LINES BEGIN

cp /usr/bin/mate-appearance-properties /usr/bin/mate-appearance-properties-old

cp /usr/bin/mate-window-properties /usr/bin/mate-window-properties-old

echo '#!/bin/bash

shock-backgrounds' | tee /usr/bin/mate-appearance-properties

echo '#!/bin/bash

shock-wm-settings' | tee /usr/bin/mate-window-properties

cp -r /usr/share/themes/shock-* /etc/skel/.themes

cp -r /usr/share/shock/install-temp/"Sample Videos" /etc/skel/Videos

echo "shock_gtk_theme=shock-light-blue
shock_icon_theme=shock-light-blue" | tee /etc/skel/.config/shock_themes




