#!/bin/bash

#use this in the preupgr or postupgr script in the 9.0 upgrade pack for a smooth transition

#the config file renaming begins

for user_home_dir in /home/*
do

    if [[ -f "$user_home_dir"/.config/shock-slideshow-wallpaper ]]
    then

        source "$user_home_dir"/.config/shock-slideshow-wallpaper

        echo "directory=\"$directory\"

delay=\"$delay\"

random_boolean=\"$random_inorder\"

style=\"$style\"" | tee "$user_home_dir"/.config/shock/slideshow-background

        rm "$user_home_dir"/.config/shock-slideshow-wallpaper

        rm "$user_home_dir"/.config/shock-wallpaper

        source "$user_home_dir"/.config/shock_themes

        echo "shock_gtk_theme=shock-${lod}-${color}
    shock_icon_theme=shock-${lod}-${color}" | tee "$user_home_dir"/.config/shock/themes

        rm "$user_home_dir"/.config/shock_themes

        rm -r "$user_home_dir"/.cache/shock-release-scanner

        mv "$user_home_dir"/.config/shock-welcome-indicator "$user_home_dir"/.config/shock/welcome-indicator

        mv "$user_home_dir"/.config/userlogstat "$user_home_dir"/.config/shock/userlogstat

        mv "$user_home_dir"/.config/shock_fonts "$user_home_dir"/.config/shock/fonts

    fi

done

#the config file renaming ends

#the pcstl -> screentime patch begins

chattr -R -i /usr/share/shock-pcstl

rm -r /usr/share/shock-pcstl/*/today

for user_pcstl_dir in /usr/share/shock-pcstl/*
do

    mv "$user_pcstl_dir"/shock-screen-time-limit "$user_pcstl_dir"/dailylimit

done

mkdir -p /usr/share/shock-screentime

mv /usr/share/shock-pcstl/* /usr/share/shock-screentime/

rm -r /usr/share/shock-pcstl

#the pcstl -> screentime patch ends
