#!/usr/bin/env python3

import sys
import gi
gi.require_version('Gtk', '4.0')
from gi.repository import Gtk, GObject, Gio, Gdk
import argparse
import magic
mime = magic.Magic(mime=True)
import subprocess
from pathlib import Path
from PIL import Image

parser = argparse.ArgumentParser(description="Desktop background selection tool for MATE desktop")

parser.add_argument("-v", "--verbose", action="store_true", help="Enable verbose output")

args = parser.parse_args()

def log(message):
    if args.verbose:
        print(message)

class app(Gtk.Application):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.connect('activate', self.on_activate)

    def on_activate(self, app):
        # Create a Builder
        builder = Gtk.Builder()
        builder.add_from_file("main.ui")

        # Obtain the GSettings objects
        self.bg_settings = Gio.Settings.new("org.mate.background")
        self.desktop_icon_settings = Gio.Settings.new("org.mate.caja.desktop")
        self.slideshow_bg_settings = Gio.Settings.new("net.shockos.mate.backgrounds.slideshow")
        self.slideshow_bg_settings.connect("changed", self.refresh)

        # Obtain the widgets
        self.slideshow_bg_switch = builder.get_object("slideshow_bg_switch")
        self.slideshow_bg_settings.bind("enabled", self.slideshow_bg_switch, "active", Gio.SettingsBindFlags.DEFAULT)
        self.slideshow_bg_grid = builder.get_object("slideshow_bg_grid")
        self.slideshow_bg_mins_entry = builder.get_object("slideshow_bg_mins_entry")
        self.slideshow_bg_mins_entry.connect("changed", self.update_interval)
        self.slideshow_bg_mins_entry.set_text(str(self.slideshow_bg_settings.get_uint("interval")))
        self.slideshow_bg_mins_add_button = builder.get_object("slideshow_bg_mins_add_button")
        self.slideshow_bg_mins_add_button.connect("clicked", self.mins_math)
        self.slideshow_bg_mins_sub_button = builder.get_object("slideshow_bg_mins_sub_button")
        self.slideshow_bg_mins_sub_button.connect("clicked", self.mins_math)
        self.slideshow_bg_order_cb = builder.get_object("slideshow_bg_order_cb")
        self.slideshow_bg_settings.bind("order", self.slideshow_bg_order_cb, "active-id", Gio.SettingsBindFlags.DEFAULT)

        self.file_chooser_button = builder.get_object("file_chooser_button")
        self.file_chooser_button.connect("clicked", self.open_file)
        self.file_chooser = builder.get_object("file_chooser")
        self.file_chooser.connect("response", self.parse_file)
        self.picture_filename_label = builder.get_object("picture_filename_label")
        self.bg_settings.bind("picture-filename", self.picture_filename_label, "label", Gio.SettingsBindFlags.DEFAULT)
        self.style_cb = builder.get_object("style_cb")
        self.bg_settings.bind("picture-options", self.style_cb, "active-id", Gio.SettingsBindFlags.DEFAULT)
        self.bg_color_shading_cb = builder.get_object("bg_color_shading_cb")
        self.bg_color_shading_cb.connect("notify", self.bg_color_shading_changed)
        self.bg_settings.bind("color-shading-type", self.bg_color_shading_cb, "active-id", Gio.SettingsBindFlags.DEFAULT)
        self.primary_color_button = builder.get_object("primary_color_button")
        self.secondary_color_button = builder.get_object("secondary_color_button")
        self.reset_all_button = builder.get_object("reset_all_button")
        self.reset_all_button.connect("clicked", self.reset_all)

        self.error_message = builder.get_object("error_message")

        # Order is important here
        self.get_bg_colors()
        self.primary_color_button.connect("notify", self.bg_colors_changed)
        self.secondary_color_button.connect("notify", self.bg_colors_changed)

        
        self.desktop_icons_checkboxes_box = builder.get_object("desktop_icons_checkboxes_box")
        self.show_desktop_icons_switch = builder.get_object("show_desktop_icons_switch")
        self.show_desktop_icons_switch.connect("notify", self.desktop_icons_switched)
        self.bg_settings.bind("show-desktop-icons", self.show_desktop_icons_switch, "active", Gio.SettingsBindFlags.DEFAULT)
        self.computer_checkbox = builder.get_object("computer_checkbox")
        self.desktop_icon_settings.bind("computer-icon-visible", self.computer_checkbox, "active", Gio.SettingsBindFlags.DEFAULT)
        self.home_checkbox = builder.get_object("home_checkbox")
        self.desktop_icon_settings.bind("home-icon-visible", self.home_checkbox, "active", Gio.SettingsBindFlags.DEFAULT)
        self.trash_checkbox = builder.get_object("trash_checkbox")
        self.desktop_icon_settings.bind("trash-icon-visible", self.trash_checkbox, "active", Gio.SettingsBindFlags.DEFAULT)
        self.network_checkbox = builder.get_object("network_checkbox")
        self.desktop_icon_settings.bind("network-icon-visible", self.network_checkbox, "active", Gio.SettingsBindFlags.DEFAULT)
        self.mounted_volumes_checkbox = builder.get_object("mounted_volumes_checkbox")
        self.desktop_icon_settings.bind("volumes-visible", self.mounted_volumes_checkbox, "active", Gio.SettingsBindFlags.DEFAULT)

        
        self.bg_color_shading_changed(None, None)
        self.desktop_icons_switched(None, None)

        # Obtain and show the main window
        self.refresh()
        self.main_window = builder.get_object("main_window")
        self.file_chooser.set_transient_for(self.main_window)
        self.error_message.set_transient_for(self.main_window)
        self.main_window.set_application(self)  # Application will close once it no longer has active windows attached to it
        self.main_window.present()

    def open_file(self, button):
        if self.slideshow_bg_settings.get_boolean("enabled"):
            self.file_chooser.set_action(Gtk.FileChooserAction.SELECT_FOLDER)
        else:
            self.file_chooser.set_action(Gtk.FileChooserAction.OPEN)
        file = self.file_chooser.show()

    def parse_file(self, file, file_chooser):
        file = file.get_file().get_path()
        if self.slideshow_bg_settings.get_boolean("enabled"):
            file = Path(file)
            def checkdir():
                for item in file.iterdir():
                    if item.is_file():
                        try:
                            with Image.open(item) as img:
                                return True # If PIL can open it, it's an image
                        except Exception:
                            pass # Not an image, continue checking
                return False
            if Path.is_dir(file):
                if checkdir():
                    self.slideshow_bg_settings.set_string("folder", file)
                else:
                    self.error_message.set_visible(True)
            else:
                self.error_message.set_visible(True)
        else:
            file_type = mime.from_file(file)
            if file_type.startswith('image/'):
                self.bg_settings.set_string("picture-filename", file)
            else:
                self.error_message.set_visible(True)
                log(f"ERROR: {file} is not an image.")

    def get_bg_colors(self):
        def get_rgba(string):
            color = Gdk.RGBA()
            hexcode = self.bg_settings.get_string(string)
            r = int(hexcode[1:3], 16) / 255.0
            color.red = r
            g = int(hexcode[3:5], 16) / 255.0
            color.green = g
            b = int(hexcode[5:7], 16) / 255.0
            color.blue = b
            color.alpha = 1
            return color
        primary_color = get_rgba("primary-color")
        secondary_color = get_rgba("secondary-color")
        self.primary_color_button.set_rgba(primary_color)
        self.secondary_color_button.set_rgba(secondary_color)
        log(f"PRIMARY_COLOR: {primary_color}")
        log(f"SECONDARY_COLOR: {secondary_color}")

    def bg_colors_changed(self, button, state):
        def parse_color(widget):
            color = widget.get_rgba()
            r = int(color.red * 255)
            g = int(color.green * 255)
            b = int(color.blue * 255)
            return f"#{r:02X}{g:02X}{b:02X}"
        primary_color = parse_color(self.primary_color_button)
        secondary_color = parse_color(self.secondary_color_button)
        self.bg_settings.set_string("primary-color", primary_color)
        self.bg_settings.set_string("secondary-color", secondary_color)
        log(f"PRIMARY_COLOR: {primary_color}")
        log(f"SECONDARY_COLOR: {secondary_color}")

    def bg_color_shading_changed(self, cb, active):
        if self.bg_color_shading_cb.get_active_id() == "solid":
            self.secondary_color_button.set_visible(False)
        else:
            self.secondary_color_button.set_visible(True)

    def desktop_icons_switched(self, switch, state):
        if self.show_desktop_icons_switch.get_active():
            self.desktop_icons_checkboxes_box.set_sensitive(True)
        else:
            self.desktop_icons_checkboxes_box.set_sensitive(False)

    def mins_math(self, widget):
        mins = int(self.slideshow_bg_mins_entry.get_text())
        if widget == self.slideshow_bg_mins_add_button:
            mins = mins + 1
        elif widget == self.slideshow_bg_mins_sub_button:
            if (mins > 1):
                mins = mins - 1
        self.slideshow_bg_mins_entry.set_text(str(mins))

    def update_interval(self, entry):
        mins = int(self.slideshow_bg_mins_entry.get_text())
        if (int(mins) < 1):
            mins = 1
            self.slideshow_bg_mins_entry.set_text("1")
        self.slideshow_bg_settings.set_uint("interval", mins)

    def refresh(self):
        self.slideshow_bg_mins_entry.set_text(str(self.slideshow_bg_settings.get_uint("interval")))
        if self.slideshow_bg_settings.get_boolean("enabled"):
            self.slideshow_bg_grid.set_sensitive(True)
        else:
            self.slideshow_bg_grid.set_sensitive(False)

    def reset_all(self, button):
        subprocess.run(['gsettings', 'reset-recursively', 'org.mate.background'])
        subprocess.run(['gsettings', 'reset-recursively', 'org.mate.caja.desktop'])
        subprocess.run(['gsettings', 'reset-recursively', 'net.shockos.mate.backgrounds.slideshow'])
        self.refresh()

app = app(application_id="net.ShockOS.MATE.Backgrounds")
app.run()

