#!/bin/bash

echo "DE_EDITION=MATE" | tee -a /usr/share/shock/shock-dist-info

#the above command will replace the default Debian wallpapers with the Shock OS wallpapers

touch /etc/lightdm/slick-greeter.conf

chmod a+w /etc/lightdm/slick-greeter.conf

echo "[Greeter]
theme-name=Yaru-purple-dark
icon-theme-name=Yaru-purple-dark
show-hostname=false
show-power=false
show-keyboard=false
show-clock=false" | tee /etc/lightdm/slick-greeter.conf

#the above set of commands sets the slick-greeter settings

rm /usr/share/applications/screensavers/gnomelogo-floaters.desktop

rm /usr/share/applications/screensavers/footlogo-floaters.desktop

#the above commands set the Lightning Bolt and Raspberry screensavers

rm /usr/share/applications/display-im6.q16.desktop

rm /usr/share/applications/libreoffice-startcenter.desktop

rm /usr/share/applications/ca.desrt.dconf-editor.desktop

rm /usr/share/applications/caja-file-management-properties.desktop

rm /usr/share/applications/mate-volume-control.desktop

rm /usr/share/applications/mate-time-admin.desktop

rm /usr/share/applications/mpv.desktop

rm /usr/share/applications/mate-tweak.desktop

rm /usr/share/applications/users.desktop

rm /usr/share/applications/mate-font-viewer.desktop

rm /usr/share/applications/mate-appearance-properties.desktop

rm /usr/share/applications/compton.desktop

rm /usr/share/applications/picom.desktop

#removes the shortcuts for unwanted apps in the applications directory

#the home directory building begins

#the home directory building ends

cp /usr/bin/mate-appearance-properties /usr/bin/mate-appearance-properties-old

cp /usr/bin/mate-window-properties /usr/bin/mate-window-properties-old

echo '#!/bin/bash

shock-backgrounds' | tee /usr/bin/mate-appearance-properties

echo '#!/bin/bash

shock-wm-settings' | tee /usr/bin/mate-window-properties

#the above set of commands replaces the mate-appearance-properties program with a link to shock-wallpapers (for the desktop context menu)

systemctl enable --global shock-notifications-log-daemon

systemctl enable --global shock-slideshow-background-daemon

systemctl set-default multi-user #ensures the target is set to multi-user

gtk-update-icon-cache -f /usr/share/icons/Yaru/

cp -rf /usr/share/shock/install-temp/* /

cp -rf /usr/share/shock/install-temp/usr/share/applications/* /etc/skel/.local/share/applications #this command eliminates the need to duplicate the .desktop files

rm -r /usr/share/shock/install-temp



