#!/bin/bash

cd /

sed -i '1s/.*/PRETTY_NAME="Shock OS 9.0 Issac"/' /usr/lib/os-release

#the above set of commands copies the os release file to /usr/lib

cp -r /usr/share/shock/wallpapers/* /usr/share/wallpapers/DebianTheme/contents/images

cp -r /usr/share/shock/wallpapers/* /usr/share/desktop-base/active-theme/lockscreen/contents/images

rm /usr/share/images/desktop-base/login-background.svg

cp /usr/share/shock/login-background.svg /usr/share/images/desktop-base

#the above command will replace the default Debian wallpapers with the Shock OS wallpapers

for a in /usr/share/shock-themes/16x16/*
do

    for b in $(find /usr/share/icons -name "$(basename "$a")")
    do

        if [[ -n "$b" ]]
        then

            cp -f "/usr/share/shock-themes/$(identify -format "%wx%h" "$b")/$(basename "$a")" "$b"

        fi

    done

done

#the above command replaces GNOME and MATE start menu icons with the Shock OS logo

cp -r /usr/share/shock-themes/scalable/mate-logo.svg /usr/share/mate-menu/icons

#the above command sets the start menu icon to the Shock OS logo

cp -r /usr/share/shock/panel/* /usr/share/mate-panel/layouts

#the above command installs the Shock OS panel layout and sets it as the default

cp -r /usr/share/shock/logos/* /usr/share/desktop-base/debian-logos

#the above command replaces the Debian branding with Shock OS branding

rm /etc/lightdm/lightdm.conf

rm /usr/share/icons/mate/cursor.theme

cp /usr/share/shock/lightdm.conf /etc/lightdm

cp /usr/share/shock/lightdm-gtk-greeter.conf /etc/lightdm

cp /usr/share/shock/cursor.theme /usr/share/icons/mate

#the above set of commands sets the default Shock OS screen

touch /etc/lightdm/slick-greeter.conf

chmod a+w /etc/lightdm/slick-greeter.conf

echo "[Greeter]
theme-name=Yaru-blue
icon-theme-name=Yaru-blue-dark
show-hostname=false
show-power=false
show-keyboard=false
show-clock=false" | tee /etc/lightdm/slick-greeter.conf

#the above set of commands sets the slick-greeter settings

chmod -R a+w /usr/share/shock

echo "0" | tee /usr/share/shock/setupvalue

#the above set of commands sets the 'pi' user to automatic login

rm /usr/share/applications/mate-default-applications-properties.desktop

cp /usr/share/shock/mate-default-applications-properties.desktop /usr/share/applications

#the above command sets a star as the logo for the preferred applications

rm /usr/share/pixmaps/gnome-logo-white.svg

rm /usr/share/pixmaps/mate-logo-white.svg

rm /usr/share/applications/screensavers/gnomelogo-floaters.desktop

rm /usr/share/applications/screensavers/footlogo-floaters.desktop

cp /usr/share/shock/gnomelogo-floaters.desktop /usr/share/applications/screensavers

cp -r /usr/share/shock/gnome-logo-white.svg /usr/share/pixmaps

#the above commands set the Lightning Bolt and Raspberry screensavers

rm /usr/share/applications/yad-icon-browser.desktop

rm /usr/share/applications/display-im6.q16.desktop

rm /usr/share/applications/htop.desktop

rm /usr/share/applications/libreoffice-startcenter.desktop

rm /usr/share/applications/ca.desrt.dconf-editor.desktop

rm /usr/share/applications/caja-file-management-properties.desktop

rm /usr/share/applications/mate-volume-control.desktop

rm /usr/share/applications/mate-time-admin.desktop

rm /usr/share/applications/mpv.desktop

rm /usr/share/applications/mate-tweak.desktop

rm /usr/share/applications/users.desktop

rm /usr/share/applications/mate-font-viewer.desktop

rm /usr/share/applications/mate-appearance-properties.desktop

rm /usr/share/applications/compton.desktop

rm /usr/share/applications/picom.desktop

#removes the shortcuts for unwanted apps in the applications directory

#the home directory building begins

mkdir -p /etc/skel/Desktop

mkdir -p /etc/skel/Documents

mkdir -p /etc/skel/Downloads

mkdir -p /etc/skel/Music

mkdir -p /etc/skel/Pictures

mkdir -p /etc/skel/Public

mkdir -p /etc/skel/Templates

mkdir -p /etc/skel/Videos

mkdir -p /etc/skel/.config/menus

mkdir -p /etc/skel/.config/shock

mkdir -p /etc/skel/.cache/shock-tmp

touch /etc/skel/.config/shock/welcome-indicator

touch /etc/skel/.config/shock/userlogstat

echo 'XDG_DESKTOP_DIR="$HOME/Desktop"
XDG_DOWNLOAD_DIR="$HOME/Downloads"
XDG_TEMPLATES_DIR="$HOME/Templates"
XDG_PUBLICSHARE_DIR="$HOME/Public"
XDG_DOCUMENTS_DIR="$HOME/Documents"
XDG_MUSIC_DIR="$HOME/Music"
XDG_PICTURES_DIR="$HOME/Pictures"
XDG_VIDEOS_DIR="$HOME/Videos"' | tee /etc/skel/.config/user-dirs.dirs

cp -r /usr/share/shock/chromium /etc/skel/.config

mkdir -p /etc/skel/.cache

mkdir -p /etc/skel/.local/share/applications

cp -r /usr/share/shock/install-temp/"Sample Videos" /etc/skel/Videos

echo "shock_gtk_theme=shock-light-blue
shock_icon_theme=shock-light-blue" | tee /etc/skel/.config/shock_themes

mkdir -p /etc/skel/.themes #THEME BANDAID FIX

cp -r /usr/share/themes/shock-* /etc/skel/.themes #THEME BANDAID FIX

#the home directory building ends

cp -r /usr/share/shock/applications/* /etc/skel/.local/share/applications

cp -r /usr/share/shock/applications/* /usr/share/applications

#the above command renames the apps to Shock OS friendly names

#the XScreenSaver imperfect screensaver removal patch begins

rm /usr/share/applications/screensavers/binaryring.desktop

rm /usr/share/applications/screensavers/deluxe.desktop

rm /usr/share/applications/screensavers/fireworkx.desktop

rm /usr/share/applications/screensavers/fluidballs.desktop

rm /usr/share/applications/screensavers/fontglide.desktop

rm /usr/share/applications/screensavers/fuzzyflakes.desktop

rm /usr/share/applications/screensavers/glitchpeg.desktop

rm /usr/share/applications/screensavers/goop.desktop

rm /usr/share/applications/screensavers/interference.desktop

rm /usr/share/applications/screensavers/kumppa.desktop

rm /usr/share/applications/screensavers/metaballs.desktop

rm /usr/share/applications/screensavers/qix.desktop

rm /usr/share/applications/screensavers/rd-bomb.desktop

rm /usr/share/applications/screensavers/rocks.desktop

rm /usr/share/applications/screensavers/spotlight.desktop

rm /usr/share/applications/screensavers/strange.desktop

rm /usr/share/applications/screensavers/vidwhacker.desktop

#the XScreenSaver imperfect screensaver removal patch ends

cp /usr/bin/mate-appearance-properties /usr/bin/mate-appearance-properties-old

cp /usr/bin/mate-window-properties /usr/bin/mate-window-properties-old

echo '#!/bin/bash

shock-backgrounds' | tee /usr/bin/mate-appearance-properties

echo '#!/bin/bash

shock-wm-settings' | tee /usr/bin/mate-window-properties

#the above set of commands replaces the mate-appearance-properties program with a link to shock-wallpapers (for the desktop context menu)

echo 'ALL ALL=NOPASSWD:/usr/bin/shock-update-manager-refresh' | tee /etc/sudoers.d/shock-update-manager-refresh

#the above command allows anyone to run shock-pcstl manager without a password (for parental controls screen time limits)

echo 'ALL ALL=NOPASSWD:/usr/bin/shock-themes-sync' | tee /etc/sudoers.d/shock-themes-sync-daemon

#the above command allows users to create a symlink to their custom themes in /usr/share/themes so that root apps can use their user-specific themes

echo 'ALL ALL=NOPASSWD:/usr/bin/shock-fonts-sync' | tee /etc/sudoers.d/shock-fonts-sync-daemon

#the above command allows users to create a symlink to their custom fonts in /usr/share/fonts so that root apps can use their user-specific fonts

#Wi-Fi patch begins

echo "denyinterfaces wlan0" | tee -a /etc/dhcpcd.conf

echo "[main]
plugins=ifupdown,keyfile
dhcp=internal

[ifupdown]
managed=true" | tee /etc/NetworkManager/NetworkManager.conf

systemctl enable NetworkManager

#Wi-Fi patch ends

systemctl set-default multi-user #ensures the target is set to multi-user

#the 'shock' temporary autologin patch begins

sed -i 's/#NAutoVTs=6/NAutoVTs=1/g' /etc/systemd/logind.conf

echo '[Service]
ExecStart=
ExecStart=-/usr/sbin/agetty --autologin shock --noclear %I $TERM' | tee -a /etc/systemd/system/getty@tty1.service.d/override.conf

systemctl is-enabled getty@tty1.service

systemctl enable getty@tty1.service

systemctl daemon-reload

mkdir -p /home/shock/.config/gtk-3.0

echo "[Settings]
gtk-theme-name=shock-light-blue
gtk-icon-theme-name=shock-light-blue" | tee /home/shock/.config/gtk-3.0/settings.ini

echo 'xinit' | tee -a /home/shock/.bashrc

echo 'marco & shock-startup' | tee -a /home/shock/.xinitrc

sudo chown -R shock /home/shock

#the 'shock' temporary autologin patch ends

sed -i '$a\dtoverlay=dwc2,dr_mode=host' /boot/config.txt #this command enables the two front USB ports on the DeskPi Lite

flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo #adds the FlatHub repository

flatpak update #refreshes the flatpak cache and downloads the icons for the Shockware Center

#the systemd services patch begins

sudo systemctl daemon-reload

sudo systemctl enable shock-screentime-daemon.service

#the systemd services patch ends

#the splash screen patch begins

newcmdline="$(cat /boot/cmdline.txt) quiet splash plymouth.ignore-serial-consoles"

echo "$newcmdline" | tee /boot/cmdline.txt

echo "[Daemon]
Theme=shockspin
ShowDelay=4
Enable=1" | tee /etc/plymouth/plymouthd.conf

#the splash screen patch ends

rm -rf /usr/share/shock/install-temp



