#!/bin/bash

#the root check element begins

if [[ "$(id -u)" != "0" ]]
then

    echo "Script must be run as root. Exiting..."

    exit

fi

#the root check element ends

current_version="$(apt-show-versions shock-os-metapackage | cut -d" " -f2-2)"

if [[ "$current_version" == "." ]]
then

	current_version="${current_version%%.*}"

fi

rm /usr/share/shock-release-upgrader/codenames

wget --timeout 5 https://raw.githubusercontent.com/Shock-OS/Shock-OS/development/upgrades/codenames -P /usr/share/shock-release-upgrader

if  [[ ! -f /usr/share/shock-release-upgrader/codenames ]]
then

	echo "An internet connection is required. Exiting..."

	exit

fi

latest_version="$(cat /usr/share/shock-release-upgrader/codenames | wc -l)"

if ((latest_version>current_version))
then

	upgrto_version=$((current_version+1))

	upgrto_version_codename="$(sed -n "$upgrto_version"p /usr/share/shock-release-upgrader/codenames)"

	if ((upgrto_version<10))
	then

		upgrto_version_display_name="$upgto_version.0"

	else

		upgrto_version_display_name="$upgrto_version"

	fi

	yad --notification --image=/shock/shock-release-upgrader.svg --icon-size=48 --text="The upgrade to Shock OS $upgrto_version_display_name $upgrto_version_codename is available. Click to upgrade."

	zenity --info --window-icon=/shock/shock-release-upgrader.svg --title="Prepare to Upgrade" --text="Before upgrading, please make sure of the following:

1. The system is connected to a constant power supply.

2. The internet connection is stable and reliable.

3. No APT packages are being installed, removed or upgraded.

NOTE: The logout and power options in the start menu will be temporarily disabled while upgrading because powering off the machine during the upgrade process is highly discouraged and may render your system unusable.

Please press 'Continue' when you are ready to go on." --width=500 --ok-label="Continue"

	wget 

	



















