#!/bin/bash

cd /

sed -i '1s/.*/PRETTY_NAME="Shock OS 9.0 Issac"/' /usr/lib/os-release

#the above set of commands copies the os release file to /usr/lib

cp -r /usr/share/shock/wallpapers/* /usr/share/wallpapers/DebianTheme/contents/images

cp -r /usr/share/shock/wallpapers/* /usr/share/desktop-base/active-theme/lockscreen/contents/images

rm /usr/share/images/desktop-base/login-background.svg

cp /usr/share/shock/login-background.svg /usr/share/images/desktop-base

#the above command will replace the default Debian wallpapers with the Shock OS wallpapers

for a in /usr/share/shock-themes/icons/symbolic/16x16/*
do

    for b in $(find /usr/share/icons -name "$(basename "$a")")
    do

        if [[ -n "$b" ]]
        then

            cp -f "/usr/share/shock-themes/icons/symbolic/$(identify -format "%wx%h" "$b")/$(basename "$a")" "$b"

        fi

    done

done

#the above command replaces GNOME and MATE start menu icons with the Shock OS logo

cp -r /usr/share/shock/logos/* /usr/share/desktop-base/debian-logos

#the above command replaces the Debian branding with Shock OS branding

chmod -R a+w /usr/share/shock

echo "0" | tee /usr/share/shock/setupvalue

#the above set of commands sets the 'shock' user to automatic login

#the home directory building begins

mkdir -p /etc/skel/Desktop

mkdir -p /etc/skel/Documents

mkdir -p /etc/skel/Downloads

mkdir -p /etc/skel/Music

mkdir -p /etc/skel/Pictures

mkdir -p /etc/skel/Public

mkdir -p /etc/skel/Templates

mkdir -p /etc/skel/Videos

mkdir -p /etc/skel/.config/menus

mkdir -p /etc/skel/.config/shock

mkdir -p /etc/skel/.cache/shock-tmp

touch /etc/skel/.config/shock/welcome-indicator

touch /etc/skel/.config/shock/userlogstat

echo 'XDG_DESKTOP_DIR="$HOME/Desktop"
XDG_DOWNLOAD_DIR="$HOME/Downloads"
XDG_TEMPLATES_DIR="$HOME/Templates"
XDG_PUBLICSHARE_DIR="$HOME/Public"
XDG_DOCUMENTS_DIR="$HOME/Documents"
XDG_MUSIC_DIR="$HOME/Music"
XDG_PICTURES_DIR="$HOME/Pictures"
XDG_VIDEOS_DIR="$HOME/Videos"' | tee /etc/skel/.config/user-dirs.dirs

cp -r /usr/share/shock/chromium /etc/skel/.config

mkdir -p /etc/skel/.cache

mkdir -p /etc/skel/.local/share/applications

cp -r /usr/share/shock/install-temp/"Sample Videos" /etc/skel/Videos

echo 'shock_gtk_theme=Yaru-blue
shock_icon_theme=Yaru-blue
use_libadwaita_theme=FALSE' | tee /etc/skel/.config/shock/themes

cp /usr/share/shock/face /etc/skel/.face

#the home directory building ends

cp -r /usr/share/shock/applications/* /etc/skel/.local/share/applications

cp -r /usr/share/shock/applications/* /usr/share/applications

#the above command renames the apps to Shock OS friendly names

echo 'ALL ALL=NOPASSWD:/usr/bin/shock-update-manager-refresh' | tee /etc/sudoers.d/shock-update-manager-refresh

#the above command allows anyone to run shock-pcstl manager without a password (for parental controls screen time limits)

echo 'ALL ALL=NOPASSWD:/usr/bin/shock-themes-sync' | tee /etc/sudoers.d/shock-themes-sync-daemon

#the above command allows users to create a symlink to their custom themes in /usr/share/themes so that root apps can use their user-specific themes

echo 'ALL ALL=NOPASSWD:/usr/bin/shock-fonts-sync' | tee /etc/sudoers.d/shock-fonts-sync-daemon

#the above command allows users to create a symlink to their custom fonts in /usr/share/fonts so that root apps can use their user-specific fonts

systemctl set-default multi-user #ensures the target is set to multi-user

#the 'shock' temporary autologin patch begins

sed -i 's/#NAutoVTs=6/NAutoVTs=1/g' /etc/systemd/logind.conf

echo '[Service]
ExecStart=
ExecStart=-/usr/sbin/agetty --autologin shock --noclear %I $TERM' | tee -a /etc/systemd/system/getty@tty1.service.d/override.conf

systemctl is-enabled getty@tty1.service

systemctl enable getty@tty1.service

systemctl daemon-reload

#the 'shock' temporary autologin patch ends

sed -i '$a\dtoverlay=dwc2,dr_mode=host' /boot/firmware/config.txt #this command enables the two front USB ports on the DeskPi Lite

flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo #adds the FlatHub repository

flatpak update #refreshes the flatpak cache and downloads the icons for the Shockware Center

flatpak install --assumeyes org.gtk.Gtk3theme.Yaru org.gtk.Gtk3theme.Yaru-dark org.gtk.Gtk3theme.Yaru-Blue org.gtk.Gtk3theme.Yaru-Blue-dark org.gtk.Gtk3theme.Yaru-magenta org.gtk.Gtk3theme.Yaru-magenta-dark org.gtk.Gtk3theme.Yaru-olive org.gtk.Gtk3theme.Yaru-olive-dark org.gtk.Gtk3theme.Yaru-prussiangreen org.gtk.Gtk3theme.Yaru-prussiangreen-dark org.gtk.Gtk3theme.Yaru-Purple org.gtk.Gtk3theme.Yaru-Purple-dark org.gtk.Gtk3theme.Yaru-Red org.gtk.Gtk3theme.Yaru-Red-dark org.gtk.Gtk3theme.Yaru-sage org.gtk.Gtk3theme.Yaru-sage-dark

#the systemd services patch begins

sudo systemctl daemon-reload

sudo systemctl enable shock-screentime-daemon.service

#the systemd services patch ends

#the splash screen patch begins

newcmdline="$(cat /boot/cmdline.txt) quiet splash plymouth.ignore-serial-consoles"

echo "$newcmdline" | tee /boot/cmdline.txt

echo "[Daemon]
Theme=shockspin
ShowDelay=0
Enable=1" | tee /etc/plymouth/plymouthd.conf

rm /usr/share/plymouth/themes/debian-theme

ln -s /usr/share/plymouth/themes/shockspin /usr/share/plymouth/themes/debian-theme

update-initramfs -u

#the splash screen patch ends

rm -rf /usr/share/shock/install-temp



