#!/bin/bash

sudo python3 /usr/libexec/shockos/edit-dist-info.py --deskenv="GNOME"
echo "Hidden=true" | tee -a /usr/share/applications/org.gnome.font-viewer.desktop
systemctl enable --global shockos-gnome-desktop-icons-daemon
systemctl enable --global shockos-gnome-theme-daemon
systemctl set-default multi-user #ensures the target is set to multi-user
rsync -rl --keep-dirlinks /usr/share/shockos/install-temp/* /
rm -r /usr/share/shockos/install-temp
dconf update

/usr/libexec/shockos/brand.sh

apps_to_hide=('/usr/share/applications/zutty.desktop')

for app in ${apps_to_hide[@]}
do
    if grep -q '^NoDisplay=' "$app"
    then
        sed -i '/^NoDisplay=/c\NoDisplay=true' "$app"
    else
        echo 'NoDisplay=true' | tee -a "$app"
    fi
done

