#!/bin/bash

#THE COMMAND_HERE SEGMENT BEGINS

    # Launch the command in the background and capture its PID
    COMMAND_HERE > /dev/null 2>&1 & command_pid=$!

    # Show the progress window using yad
    {

    yad --window-icon=ICON HERE --title="TITLE HERE" --text="TEXT HERE" --progress --pulsate --progress-text="" --width=300 --height=100 --button="Cancel"\!gtk-cancel:1

    ex=$?

    if [[ "$ex" != "0" ]]
    then

        kill -9 "$command_pid"
        
    fi

    } &

    # Wait for the command to finish
    wait "$command_pid"

    # Get the command's exit code
    ex=$?

    # Close the yad progress window (if it's still open)
    pkill -f "PASTE YAD COMMAND WITH NO QUOTES OR BACKSLASHES"

    # Check if the command exited with a non-zero code and show an error message if needed
    if [[ "$ex" != "0" ]]
    then

        yad --window-icon=ICON HERE --image=emblem-important --title="ERROR" --text="TEXT HERE" --button="Exit"\!gtk-cancel ; kill $$

    fi

#THE COMMAND_HERE SEGMENT ENDS
