#!/bin/bash

function yad() {

GDK_BACKEND=x11 /usr/bin/yad "$@"

}

yad --window-icon="[ICON HERE]" --title="Backups" --button="Create New Backup":0 --button="Restore Backup":1

ex=$?

if [[ "$ex" == "0" ]] #Create New Backup
then

    yad --window-icon="[ICON HERE]" --title="Backups" --form \
        --field="What to back up?"











#SOFTWARE SELECTION BACKUP:

output_file="$(yad --window-icon="[ICON HERE]" --title="Backups" --file --save)"

if [[ "$output_file" != *".zip" ]]
then

    output_file="${output_file}.zip"

fi

tmpdir="$(mktemp -d)"

echo "shock_backup_type=software_selection" | tee "$tmpdir"/shock-backup-metainfo

apt_packages=($(dpkg --get-selections | grep -v deinstall | awk '{print $1}'))

flatpak_apps=($(flatpak list --columns=app))

echo "${apt_packages[@]}" | tee "$tmpdir"/apt.list

echo "${flatpak_apps[@]}" | tee "$tmpdir"/flatpak.list

zip "$output_file" "$tmpdir"/apt.list "$tmpdir"/flatpak.list "$tmpdir"/shock-backup-metainfo






