#!/bin/bash

#the root check element begins

if (($(id -u)!=0))
then

    echo "Script must be run as root. Exiting..."

    exit

fi

#the root check element ends

version="$1"

edition="$2"

arch="$3"

device="$4"
