import argparse
import sys
sys.path.append('/usr/share/shockos')
try:
    import dist_info
except:
    print("ERROR: /usr/lib/shockos/dist_info.py appears to be corrupted, attempting to fix it...")
    with open ('/usr/lib/shockos/dist_info.py', 'w') as dist_info:
        dist_info.write(f'# DO NOT EDIT THIS FILE, DOING SO WILL CAUSE YOUR SYSTEM TO FUNCTION IMPROPERLY\n\ ')

parser = argparse.ArgumentParser(description="A simple argument parser example")

parser.add_argument('--full-name', help="Specify the full name")
parser.add_argument('--version-number', help="Specify the version number")
parser.add_argument('--edition', help="Specify the edition (desktop environment)")
parser.add_argument('--build-date', help="Specify the build date")

args = parser.parse_args()

if args.full_name:
    full_name = args.full_name
else:
    full_name = getattr(dist_info, 'full_name', "")

if args.version_number:
    version_number = args.version_number
else:
    version_number = getattr(dist_info, 'version_number', "")

if args.edition:
    edition = args.edition
else:
    edition = getattr(dist_info, 'edition', "")

if args.build_date:
    build_date = args.build_date
else:
    build_date = getattr(dist_info, 'build_date', "")

with open('/usr/lib/shockos/dist-info.sh', 'w') as dist_info:
    dist_info.write(f'# DO NOT EDIT THIS FILE, DOING SO WILL CAUSE YOUR SYSTEM TO FUNCTION IMPROPERLY\n\
SHOCKOS_FULL_NAME="{full_name}"\n\
SHOCKOS_VERSION_NUMBER="{version_number}"\n\
SHOCKOS_DE_EDITION="{edition}"\n\
SHOCKOS_BUILD_DATE="{build_date}"')

with open('/usr/lib/shockos/dist_info.py', 'w') as dist_info:
        dist_info.write(f'# DO NOT EDIT THIS FILE, DOING SO WILL CAUSE YOUR SYSTEM TO FUNCTION IMPROPERLY\n\
full_name = "{full_name}"\n\
version_number = "{version_number}"\n\
edition = "{edition}"\n\
build_date = "{build_date}"')
