#!/usr/bin/env python3

import argparse
import sys
sys.path.append('/usr/lib/shockos/')
import shockos

parser = argparse.ArgumentParser(description='A simple argument parser example')

parser.add_argument('--full-name', help='Specify the full name')
parser.add_argument('--version-number', help='Specify the version number')
parser.add_argument('--deskenv', help='Specify the deskenv (desktop environment)')
parser.add_argument('--build-date', help='Specify the build date')

args = parser.parse_args()

if args.full_name:
    full_name = args.full_name
else:
    full_name = getattr(shockos, 'full_name', '')

if args.version_number:
    version_number = args.version_number
else:
    version_number = getattr(shockos, 'version_number', '')

if args.deskenv:
    deskenv = args.deskenv
else:
    deskenv = getattr(shockos, 'deskenv', '')

if args.build_date:
    build_date = args.build_date
else:
    build_date = getattr(shockos, 'build_date', '')

with open('/usr/lib/shockos/dist-info', 'w') as dist_info:
    dist_info.write(f'#!/bin/bash\n\
# DO NOT EDIT THIS FILE, DOING SO WILL CAUSE YOUR SYSTEM TO FUNCTION IMPROPERLY\n\
SHOCKOS_FULL_NAME="{full_name}"\n\
SHOCKOS_VERSION_NUMBER="{version_number}"\n\
SHOCKOS_DESKENV="{deskenv}"\n\
SHOCKOS_BUILD_DATE="{build_date}"')
