#!/bin/bash

echo "DE_EDITION=GNOME" | tee -a /usr/share/shock/dist-info

echo "Hidden=true" | tee -a /usr/share/applications/org.gnome.font-viewer.desktop

systemctl enable --global shock-desktop-icons-daemon

systemctl enable --global shock-theme-daemon

systemctl set-default multi-user #ensures the target is set to multi-user

cp -rf /usr/share/shock/install-temp/* /

gtk-update-icon-cache -f /usr/share/icons/Yaru/

rm -r /usr/share/shock/install-temp



