#!/usr/bin/env python3

import sys
import gi
gi.require_version('Gtk', '4.0')
from gi.repository import Gtk, GObject, Gio, Gdk
import argparse

parser = argparse.ArgumentParser(description="Desktop background selection tool for MATE desktop")

parser.add_argument("-v", "--verbose", action="store_true", help="Enable verbose output")

args = parser.parse_args()

verbose = args.verbose

class app(Gtk.Application):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.connect('activate', self.on_activate)

    def on_activate(self, app):
        # Create a Builder
        builder = Gtk.Builder()
        builder.add_from_file("main.ui")

        # Obtain the GSettings objects
        self.background_settings = Gio.Settings.new("org.mate.background")
        self.desktop_icon_settings = Gio.Settings.new("org.mate.caja.desktop")

        # Obtain the widgets
        self.picture_filename_label = builder.get_object("picture_filename_label")
        self.background_settings.bind("picture-filename", self.picture_filename_label, "label", Gio.SettingsBindFlags.DEFAULT)
        self.style_cb = builder.get_object("style_cb")
        self.background_settings.bind("picture-options", self.style_cb, "active-id", Gio.SettingsBindFlags.DEFAULT)
        self.bg_color_shading_cb = builder.get_object("bg_color_shading_cb")
        self.bg_color_shading_cb.connect("notify", self.bg_color_shading_changed)
        self.background_settings.bind("color-shading-type", self.bg_color_shading_cb, "active-id", Gio.SettingsBindFlags.DEFAULT)
        self.primary_color_button = builder.get_object("primary_color_button")
        self.secondary_color_button = builder.get_object("secondary_color_button")

        # Order is important here
        self.get_bg_colors()
        self.primary_color_button.connect("notify", self.bg_colors_changed)
        self.secondary_color_button.connect("notify", self.bg_colors_changed)

        
        self.desktop_icons_checkboxes_box = builder.get_object("desktop_icons_checkboxes_box")
        self.show_desktop_icons_switch = builder.get_object("show_desktop_icons_switch")
        self.show_desktop_icons_switch.connect("notify", self.desktop_icons_switched)
        self.background_settings.bind("show-desktop-icons", self.show_desktop_icons_switch, "active", Gio.SettingsBindFlags.DEFAULT)
        self.computer_checkbox = builder.get_object("computer_checkbox")
        self.desktop_icon_settings.bind("computer-icon-visible", self.computer_checkbox, "active", Gio.SettingsBindFlags.DEFAULT)
        self.home_checkbox = builder.get_object("home_checkbox")
        self.desktop_icon_settings.bind("home-icon-visible", self.home_checkbox, "active", Gio.SettingsBindFlags.DEFAULT)
        self.trash_checkbox = builder.get_object("trash_checkbox")
        self.desktop_icon_settings.bind("trash-icon-visible", self.trash_checkbox, "active", Gio.SettingsBindFlags.DEFAULT)
        self.network_checkbox = builder.get_object("network_checkbox")
        self.desktop_icon_settings.bind("network-icon-visible", self.network_checkbox, "active", Gio.SettingsBindFlags.DEFAULT)
        self.mounted_volumes_checkbox = builder.get_object("mounted_volumes_checkbox")
        self.desktop_icon_settings.bind("volumes-visible", self.mounted_volumes_checkbox, "active", Gio.SettingsBindFlags.DEFAULT)

        
        self.bg_color_shading_changed(None, None)
        self.desktop_icons_switched(None, None)

        # Obtain and show the main window
        self.main_window = builder.get_object("main_window")
        self.main_window.set_application(self)  # Application will close once it no longer has active windows attached to it
        self.main_window.present()

    def get_bg_colors(self):
        color = Gdk.RGBA()
        hexcode = self.background_settings.get_string("primary-color")
        r = int(hexcode[1:3], 16) / 255.0
        color.red = r
        g = int(hexcode[3:5], 16) / 255.0
        color.green = g
        b = int(hexcode[5:7], 16) / 255.0
        color.blue = b
        color.alpha = 1
        self.primary_color_button.set_rgba(color)
        color = Gdk.RGBA()
        hexcode = self.background_settings.get_string("secondary-color")
        r = int(hexcode[1:3], 16) / 255.0
        color.red = r
        g = int(hexcode[3:5], 16) / 255.0
        color.green = g
        b = int(hexcode[5:7], 16) / 255.0
        color.blue = b
        color.alpha = 1
        self.secondary_color_button.set_rgba(color)

    def bg_colors_changed(self, button, state):
        color = self.primary_color_button.get_rgba()
        r = int(color.red * 255)
        g = int(color.green * 255)
        b = int(color.blue * 255)
        color = f"#{r:02X}{g:02X}{b:02X}"
        self.background_settings.set_string("primary-color", color)
        if verbose:
            print(f"PRIMARY_COLOR: {color}")
        color = self.secondary_color_button.get_rgba()
        r = int(color.red * 255)
        g = int(color.green * 255)
        b = int(color.blue * 255)
        color = f"#{r:02X}{g:02X}{b:02X}"
        self.background_settings.set_string("secondary-color", color)
        if verbose:
            print(f"SECONDARY_COLOR: {color}")

    def bg_color_shading_changed(self, cb, active):
        if self.bg_color_shading_cb.get_active_id() == "solid":
            self.secondary_color_button.set_visible(False)
        else:
            self.secondary_color_button.set_visible(True)

    def desktop_icons_switched(self, switch, state):
        if self.show_desktop_icons_switch.get_active():
            self.desktop_icons_checkboxes_box.set_sensitive(True)
        else:
            self.desktop_icons_checkboxes_box.set_sensitive(False)

app = app(application_id="net.ShockOS.MATE.Backgrounds")
app.run()

