#!/bin/bash

sudo python3 /usr/libexec/shockos/edit-dist-info.py --edition="GNOME"
echo "Hidden=true" | tee -a /usr/share/applications/org.gnome.font-viewer.desktop
systemctl enable --global shockos-gnome-desktop-icons-daemon
systemctl enable --global shockos-gnome-theme-daemon
systemctl set-default multi-user #ensures the target is set to multi-user
rsync -rl --keep-dirlinks /usr/share/shockos/install-temp/* /
rm -r /usr/share/shockos/install-temp
dconf update

