#!/bin/bash

cp -r /usr/share/shock/wallpapers/* /usr/share/wallpapers/DebianTheme/contents/images

cp -r /usr/share/shock/wallpapers/* /usr/share/desktop-base/active-theme/lockscreen/contents/images

rm /usr/share/images/desktop-base/login-background.svg

cp /usr/share/shock/login-background.svg /usr/share/images/desktop-base

#the above command will replace the default Debian wallpapers with the Shock OS wallpapers

cp -r /usr/share/shock/logos/* /usr/share/desktop-base/debian-logos

#the above command replaces the Debian branding with Shock OS branding

cp -r /usr/share/shock-themes/scalable/mate-logo.svg /usr/share/mate-menu/icons

#the above command sets the start menu icon to the Shock OS logo

cp -r /usr/share/shock/panel/* /usr/share/mate-panel/layouts

#the above command installs the Shock OS panel layout and sets it as the default

rm /etc/lightdm/lightdm.conf

rm /usr/share/icons/mate/cursor.theme

cp /usr/share/shock/lightdm.conf /etc/lightdm

cp /usr/share/shock/lightdm-gtk-greeter.conf /etc/lightdm

cp /usr/share/shock/cursor.theme /usr/share/icons/mate

#the above set of commands sets the default Shock OS screen

touch /etc/lightdm/slick-greeter.conf

chmod a+w /etc/lightdm/slick-greeter.conf

echo "[Greeter]
theme-name=Yaru-blue-dark
icon-theme-name=Yaru-blue-dark
show-hostname=false
show-power=false
show-keyboard=false
show-clock=false" | tee /etc/lightdm/slick-greeter.conf

#the above set of commands sets the slick-greeter settings

rm /usr/share/applications/mate-default-applications-properties.desktop

cp /usr/share/shock/mate-default-applications-properties.desktop /usr/share/applications

#the above command sets a star as the logo for the preferred applications

rm /usr/share/pixmaps/gnome-logo-white.svg

rm /usr/share/pixmaps/mate-logo-white.svg

rm /usr/share/applications/screensavers/gnomelogo-floaters.desktop

rm /usr/share/applications/screensavers/footlogo-floaters.desktop

cp /usr/share/shock/gnomelogo-floaters.desktop /usr/share/applications/screensavers

cp -r /usr/share/shock/gnome-logo-white.svg /usr/share/pixmaps

#the above commands set the Lightning Bolt and Raspberry screensavers

rm /usr/share/applications/yad-icon-browser.desktop

rm /usr/share/applications/display-im6.q16.desktop

rm /usr/share/applications/htop.desktop

rm /usr/share/applications/libreoffice-startcenter.desktop

rm /usr/share/applications/ca.desrt.dconf-editor.desktop

rm /usr/share/applications/caja-file-management-properties.desktop

rm /usr/share/applications/mate-volume-control.desktop

rm /usr/share/applications/mate-time-admin.desktop

rm /usr/share/applications/mpv.desktop

rm /usr/share/applications/mate-tweak.desktop

rm /usr/share/applications/users.desktop

rm /usr/share/applications/mate-font-viewer.desktop

rm /usr/share/applications/mate-appearance-properties.desktop

rm /usr/share/applications/compton.desktop

rm /usr/share/applications/picom.desktop

#removes the shortcuts for unwanted apps in the applications directory

#the home directory building begins

cp /usr/share/shock/mate_dock_applet.conf /etc/skel/.config

cp /usr/share/shock/face /etc/skel/.face

#the home directory building ends

cp -r /usr/share/shock/applications/* /etc/skel/.local/share/applications

cp -r /usr/share/shock/applications/* /usr/share/applications

#the above command renames the apps to Shock OS friendly names

cp /usr/bin/mate-appearance-properties /usr/bin/mate-appearance-properties-old

cp /usr/bin/mate-window-properties /usr/bin/mate-window-properties-old

echo '#!/bin/bash

shock-backgrounds' | tee /usr/bin/mate-appearance-properties

echo '#!/bin/bash

shock-wm-settings' | tee /usr/bin/mate-window-properties

#the above set of commands replaces the mate-appearance-properties program with a link to shock-wallpapers (for the desktop context menu)

systemctl set-default multi-user #ensures the target is set to multi-user

#the 'shock' temporary autologin patch begins

mkdir -p /home/shock/.config/gtk-3.0

echo "[Settings]
gtk-theme-name=Yaru-blue
gtk-icon-theme-name=Yaru-blue" | tee /home/shock/.config/gtk-3.0/settings.ini

echo 'xinit' | tee -a /home/shock/.bashrc

echo 'marco & shock-startup' | tee -a /home/shock/.xinitrc

sudo chown -R shock /home/shock

#the 'shock' temporary autologin patch ends



